In [ ]:
import time

start_time = time.time() # 측정 시작

# 알고리즘

end_time = time.time() # 측정 종료

print("time: ", end_time - start_time) # 수행시간 출력

time:  1.3828277587890625e-05


In [ ]:
from itertools import permutations, combinations, product, combinations_with_replacement

data = [1,2,3]

p_data = list(permutations(data, 2))
c_data = list(combinations(data, 2))
product_data = list(product(data, repeat=2))
cwr_data = list(combinations_with_replacement(data, 2))

for n, d in zip(['순열', '조합', '중복순열', '중복조합'],[p_data, c_data, product_data, cwr_data]):
    print(f'[n] : [d]')

순열 : [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
조합 : [(1, 2), (1, 3), (2, 3)]
중복순열 : [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
중복조합 : [(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]


In [ ]:
from collections import Counter, deque, defaultdict

In [ ]:
def gcd(a, b):
    if a % b == 0:
        return b
    else:
        return gcd(b, a % b)

print(gcd(192, 162))

6


In [ ]:
print(gcd(162, 192))

6


In [ ]:
def dfs(graph, v, visited):
    visited[v] = True
    print(v, end=' ')
    
    for i in graph[v]:
        if not visited[i]:
            dfs(graph, i, visited)

graph = [
    [],
    [2,3,8],
    [1,7],
    [1,4,5],
    [3,5],
    [3,4],
    [7],
    [2,6,8],
    [1,7]
]

visited = [False] * 9

dfs(graph, 1, visited)

1 2 7 6 8 3 4 5 

In [ ]:
from collections import deque

def bfs(graph, start, visited):
    queue = deque([start])
    visited[start] = True
    
    while queue:
        v = queue.popleft()
        print(v, end=' ')
        
        for i in graph[v]:
            if not visited[i]:
                queue.append(i)
                visited[i] = True

graph = [
    [],
    [2,3,8],
    [1,7],
    [1,4,5],
    [3,5],
    [3,4],
    [7],
    [2,6,8],
    [1,7]
]

# 각 노드가 방문된 정보를 표현(1차원 리스트)
visited = [False] * 9

bfs(graph, 1, visited)

1 2 3 8 7 4 5 6 

In [ ]:
# 어피치보다 라이언이 1발 더 많이 맞추거나 아예 안 맞추거나

def solution(n, info):
    answer = [-1]
    a_info = info
    l_info = [0] * len(info)
    gap = 0
    
    def calc_score(a_info, l_info):
        # 어피치, 라이언 총 점수
        a_score = 0
        l_score = 0
        
        for i in range(len(a_info)):
            if a_info[i] > 0 or l_info[i] > 0:
                if a_info[i] >= l_info[i]:
                    a_score += (10-i)
                else:
                    l_score += (10-i)
        return (l_score > a_score, l_score - a_score)
    
    def dfs(idx, cnt):
        nonlocal answer, a_info, l_info, gap
        
        if cnt == 0 or idx == 10:
            result = calc_score(a_info, l_info)
            # 라이언이 어피치보다 점수가 높을 때
            if result[0]:
                
                # 화살이 남은 경우, 0점에 다 쏴도 이긴다.
                if cnt >= 0:
                    l_info[10] = cnt
                    
                if result[1] > gap:
                    gap = result[1]
                    answer = l_info.copy()
                
                elif result[1] == gap:
                    for i in range(len(l_info)):
                        if l_info[10-i] > answer[10-i]:
                            answer = l_info.copy()
                            break
            return
        
        # 어피치보다 1개 더 많이 맞추거나, 아예 안 맞추거나
        if cnt > a_info[idx]:
            # 1개 더 많이 맞춘 걸로 진행
            l_info[idx] = a_info[idx]+1
            dfs(idx+1, cnt-(a_info[idx]+1))
            
        # 아예 안 맞추는 걸로 진행
        l_info[idx] = 0
        dfs(idx+1, cnt)
        
    dfs(0, n)
    
    return answer

In [1]:
from collections import deque

queue = deque()

len(queue)

0

In [2]:
[1] + [2]

[1, 2]

In [20]:
import numpy as np
rectangle = [[1,1,7,4],[3,2,5,5],[4,3,6,9],[2,6,8,8]]
maps = [[0] * 10 for _ in range(10)]
nmaps = np.array(maps)
for i, r in enumerate(rectangle, start=1):
    nmaps[9-r[3]:9-r[1]+1, r[0]:r[2]+1] = i
for r in rectangle:
    nmaps[9-r[3]+1:9-r[1], r[0]+1:r[2]] = 0
print(nmaps)

[[0 0 0 0 3 3 3 0 0 0]
 [0 0 4 4 4 0 4 4 4 0]
 [0 0 4 0 0 0 0 0 4 0]
 [0 0 4 4 4 0 4 4 4 0]
 [0 0 0 2 3 0 3 0 0 0]
 [0 1 1 2 0 0 3 1 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [32]:
maps = [[0] * 10 for _ in range(10)]
nmaps = np.array(maps)
nmaps[0:3, 0:3] = 1
nmaps

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
maps = [[0] * 9 for _ in range(9)]
nmaps = np.array(maps)

nmaps[2:5, 3:7] = 1
nmaps

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
from collections import deque
import numpy as np
# bfs
def solution(rectangle, characterX, characterY, itemX, itemY):
    answer = 0
    maps = np.zeros((102,102))
    for rect in rectangle:
        x1, y1, x2, y2 = map(lambda x: x*2, rect)
        # 테두리
        maps[x1:x2+1, y1:y2+1] = 1
    for rect in rectangle:
        x1, y1, x2, y2 = map(lambda x: x*2, rect)
        # 내부
        maps[x1+1:x2, y1+1:y2] = 0
        
    start = (characterX * 2, characterY * 2)
    end = (itemX * 2, itemY * 2)
    
    def bfs(start, maps):
        nonlocal end, answer
        
        queue = deque(start)
        dx = [1, -1, 0, 0]
        dy = [0, 0, 1, -1]
        
        while queue:
            #print(queue)
            x, y = queue.popleft()
            
            for i in range(4):
                nx = x + dx[i]
                ny = y + dy[i]
                
                if nx < 0 or ny < 0 or nx >= 102 or ny >= 102:
                    continue
                
                if maps[nx][ny] == 0:
                    continue
                    
                if maps[nx][ny] == 1:
                    queue.append((nx, ny))
                    maps[nx][ny] = maps[x][y] + 1
    
    bfs([start], maps)
    answer = (maps[end[0]][end[1]]) // 2
    return answer

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
def solution(tickets):
    answer = ["ICN"]
    graph = [airport:[] for airport, _ in tickets]
    
    for airport, dst in tickets:
        graph[airport].append(dst)
    
    for airport in graph.keys():
        graph[airport].sort()
        
    def dfs(airport):
        nonlocal graph, answer
        
        if airport not in graph:
            return
        
        if len(graph) == 1:
            answer.append(graph[airport][0])
            graph.pop(airport)
            return
        
        for dst in sorted(graph[airport]):
            if (dst not in graph):
                continue
            
            graph[airport].remove(dst)
            if not graph[airport]:
                graph.pop(airport)
            answer.append(dst)
            dfs(dst)
        
    dfs("ICN")
    
    return answer

tickets = [["ICN", "AAA"], ["ICN", "AAA"], ["ICN", "AAA"], ["AAA", "ICN"], ["AAA", "ICN"]]

solution(tickets)

['ICN', 'AAA', 'ICN', 'AAA', 'ICN', 'AAA']

In [86]:
def solution(tickets):
    
    answer = ["ICN"] # 가능한 경로들을 저장할 리스트 (가능한 경로가 2개 이상일 수 있다)
    visited = [False] * len(tickets)
    
    def dfs(airport, path): 
        # 모든 경로를 탐색한 경우 return
        if len(path) == len(tickets) + 1:
            answer.append(path)
            return
        
        # 연결 노드 순회
        for idx, ticket in enumerate(tickets):
            # 티켓의 0번 인덱스가 이전 경로를 뜻하는 airport와 같고, 방문하지 않은 경로일 경우
            if ticket[0] == airport and not visited[idx]:
                visited[idx] = True
                dfs(ticket[1], path + [ticket[1]]) # +: 두 리스트 합치기, append(): 추가 [[]]
                visited[idx] = False # 만약 가능한 경로가 두 개일 경우 고려
                
    dfs("ICN", ["ICN"])

    return answer[-1]

tickets = [["ICN", "AAA"], ["ICN", "AAA"], ["ICN", "AAA"], ["AAA", "ICN"], ["AAA", "ICN"]]

solution(tickets)

['ICN', 'AAA', 'ICN', 'AAA', 'ICN', 'AAA']

In [114]:
from collections import defaultdict

def solution(edges):
    new_node, donut, stick, eight = 0,0,0,0
    candidate = []
    
    visited = [False] * (max(edges, key=lambda x: x[0])[0]+1)
    print(visited)
    graph = defaultdict(list)
    for start, end in edges:
        graph[start].append(end)
    print(graph.values())
    def dfs(idx, graph, figure):
        nonlocal visited
        visited[idx] = True
        
        for node in graph[idx]:
            if node not in figure:
                
                if node == figure[0]:
                    dfs(node, graph, figure+[node])
                    
                dfs(node, graph, figure+[node])
        return figure
        
    for idx, visit in enumerate(visited):
        if idx != 0 and not visit:
            figure = dfs(idx, graph, [idx])
            candidate.append(figure)
            
    print(candidate)
        
    return new_node

#edges= [[4, 11], [1, 12], [8, 3], [12, 7], [4, 2], [7, 11], [4, 8], [9, 6], [10, 11], [6, 10], [3, 5], [11, 1], [5, 3], [11, 9], [3, 8]]
edges = [[2, 3], [4, 3], [1, 1], [2, 1]]

solution(edges)

[False, False, False, False, False]
dict_values([[3, 1], [3], [1]])
[[1], [2], [4]]


0

In [128]:
from collections import defaultdict

def solution(edges):
    new, donut, stick, eight = 0,0,0,0
    graph = defaultdict(list)
    for start, end in edges:
        graph[start].append(end)
    # 새로운 정점 찾기
    for node in graph.keys():
        if len(graph[node]) >= 2 and (node not in [edge[1] for edge in edges]):
            new = node
    visited = [False] * (max(edges, key=lambda x: x[0])[0]+1)
    def dfs(node, graph, visited, figure):
        nonlocal donut, stick, eight
        visited[node] = True
        
        # donut
        if node == graph[node][0] or (node == figure[0] and len(graph[node]) == 1):
            donut += 1
            return
        
        # stick
        if not graph[node]:
            stick += 1
            return
        
        # eight
        if node in figure and len(graph[node]) >= 2:
            eight += 1
            return
        
        for next_node in graph[node]:
            if not visited[next_node]:
                dfs(next_node, graph, visited, figure + [next_node])
            if len(graph[next_node]) >= 2:
                dfs(next_node, graph, visited, figure + [next_node])
    
    for node in graph[new]:
        print(node)
        dfs(node, graph, visited, [node])
        
    return [new, donut, stick, eight]

#edges= [[4, 11], [1, 12], [8, 3], [12, 7], [4, 2], [7, 11], [4, 8], [9, 6], [10, 11], [6, 10], [3, 5], [11, 1], [5, 3], [11, 9], [3, 8]]
edges = [[2, 3], [4, 3], [1, 1], [2, 1]]

solution(edges)

3


IndexError: list index out of range

In [148]:
from itertools import combinations

def solution(dice):
    answer = []
    n = len(dice)
    a_dice = list(combinations(range(n), n // 2))
    cnt, win = 0, 0
    
    for a in a_dice:
        b = [i for i in range(n) if i not in a]
        
        a_res = []
        for i in dice[a[0]]:
            for j in dice[a[1]]:
                a_res.append(i + j)
        b_res = []
        for i in dice[b[0]]:
            for j in dice[b[1]]:
                b_res.append(i + j)
        
        for i in a_res:
            for j in b_res:
                if i > j:
                    win += 1
                    
        cnt = len(a_res)
        
        answer.append([a, win/cnt])
    
    
    return max(answer, key=lambda x: x[-1])[0]

#dice = [[40, 41, 42, 43, 44, 45], [43, 43, 42, 42, 41, 41], [1, 1, 80, 80, 80, 80], [70, 70, 1, 1, 70, 70]]
dice = [[1, 2, 3, 4, 5, 6], [2, 2, 4, 4, 6, 6]]
solution(dice)

IndexError: tuple index out of range

In [155]:
dice = [[40, 41, 42, 43, 44, 45], [43, 43, 42, 42, 41, 41], [1, 1, 80, 80, 80, 80], [70, 70, 1, 1, 70, 70]]
a = list(combinations(dice, len(dice)//2))

In [179]:
dice = [[1, 2, 3, 4, 5, 6], [3, 3, 3, 3, 4, 4], [1, 3, 3, 4, 4, 4], [1, 1, 4, 4, 5, 5]]
a = [(0, 1), (0, 2), (0, 3)]
aa = (0, 1)
b = list(map(lambda x: dice[x], aa))
b

[[1, 2, 3, 4, 5, 6], [3, 3, 3, 3, 4, 4]]

In [186]:
from itertools import combinations, product
from bisect import bisect_left

def solution(dice):
    answer = []
    
    # a, b 주사위 선택
    n = len(dice)
    comb = list(combinations(range(n), n // 2))
    a_dice, b_dice = comb[:len(comb)//2], comb[len(comb)//2:][::-1]
    
    # 
    max_win, a_win, b_win = 0, 0, 0
    for a, b in zip(a_dice, b_dice):
        a_dices = list(map(lambda x: dice[x], a))
        b_dices = list(map(lambda x: dice[x], b))

        a_res, b_res = [], []
        for i in product(*a_dices):
            a_res.append(sum(i))
        for i in product(*b_dices):
            b_res.append(sum(i))
        
        b_res.sort()
        l = len(b_res)
        for i in a_res:
            r = bisect_left(b_res, i)
            
        
        for i in product(a_res, b_res):
            if i[0] > i[1]:
                a_win += 1
            elif i[0] < i[1]:
                b_win += 1
        
        if a_win > b_win and max_win < a_win:
            max_win = a_win
            answer = sorted(map(lambda x: x+1, [*a]))
            a_win, b_win = 0, 0
            
        elif a_win < b_win and max_win < b_win:
            max_win = b_win
            answer = sorted(map(lambda x: x+1, [*b]))
            a_win, b_win = 0, 0
            
        a_win, b_win = 0, 0
        
    return answer

(4, 2)
(4, 2)
(4, 5)
(4, 5)
(4, 6)
(4, 6)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 2)
(4, 2)
(4, 5)
(4, 5)
(4, 6)
(4, 6)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 2)
(4, 2)
(4, 5)
(4, 5)
(4, 6)
(4, 6)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 2)
(4, 2)
(4, 5)
(4, 5)
(4, 6)
(4, 6)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 4)
(4, 4)
(4, 7)
(4, 7)
(4, 8)
(4, 8)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)
(4, 9)
(4, 5)
(4, 5)
(4, 8)
(4, 8)
(4, 9)

[]

In [187]:
from itertools import combinations, product
from bisect import bisect_left

def solution(dice):
    answer = []
    
    # a, b 주사위 선택
    n = len(dice)
    a_dice = list(combinations(range(n), n // 2))
    b_dice = list(combinations(range(n), n // 2))[::-1]
    
    max_win, a_win = 0, 0
    for a, b in zip(a_dice, b_dice):
        a_dices = list(map(lambda x: dice[x], a))
        b_dices = list(map(lambda x: dice[x], b))
        a_res, b_res = []
        for i in product(*a_dices):
            a_res.append(sum(i))
        for i in product(*b_dices):
            b_res.append(sum(i))
        b_res.sort()
        l = len(b_res)
        
        for i in a_res:
            r = bisect_left(b_res, i)
            #print(r)
            a_win += r
            
        if max_win < a_win:
            max_win = a_win
            answer = sorted(map(lambda x: x+1, [*a]))
            a_win = 0
            
        a_win = 0
        
    return answer

dice = [[1, 2, 3, 4, 5, 6], [3, 3, 3, 3, 4, 4], [1, 3, 3, 4, 4, 4], [1, 1, 4, 4, 5, 5]]
solution(dice)

ValueError: not enough values to unpack (expected 2, got 0)

In [200]:
import numpy as np
from collections import defaultdict

def rotate(maps, i):
    nmap = np.array(maps)
    return np.rot90(nmap, i)

def make_figure(maps):

    def dfs(coord, maps):
        nonlocal figure
        dx = [(1,'d'), (-1,'u'), (0,'r'), (0,'l')]
        dy = [(0,'d'), (0,'u'), (1,'r'), (-1,'l')]
        x, y = coord
        
        for i in range(4):
            nx = x + dx[i][0]
            ny = y + dy[i][0]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 0:
                continue
                
            if maps[nx][ny]:
                maps[x][y] = 0
                figure = figure+dx[i][1]
                dfs((nx, ny), maps)
                
        return figure
    
    figures = defaultdict(bool)
    for x in range(len(maps)):
        for y in range(len(maps[0])):
            if maps[x][y]:
                figure = ''
                figure = dfs((x,y), maps)
                if figure != '':
                    figures[figure] = False
    
    return figures
            

def solution(game_board, table):
    answer = 0
    l = len(game_board)
    game_boards = [np.array(game_board), rotate(game_board, 1),
                   rotate(game_board, 2), rotate(game_board, 3)]
    
    figures = make_figure(table)
    
    def dfs(coord, maps):
        nonlocal figure, cnt
        dx = [(1,'d'), (-1,'u'), (0,'r'), (0,'l')]
        dy = [(0,'d'), (0,'u'), (1,'r'), (-1,'l')]
        x, y = coord
        
        for i in range(4):
            nx = x + dx[i][0]
            ny = y + dy[i][0]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 1:
                continue
                
            if maps[nx][ny] == 0:
                maps[x][y] = 1
                figure = figure+dx[i][1]
                cnt += 1
                dfs((nx, ny), maps)
                
        return figure, cnt
    
    for maps in game_boards:
        print(maps)
        for x in range(l):
            for y in range(l):
                if maps[x][y] == 0:
                    figure = ''
                    cnt = 1
                    figure, cnt = dfs((x,y), maps)
                    if (figure in figures.keys()) and (not figures[figure]):
                        figures[figure] = True
                        print(figure, cnt)
                        answer += cnt
    
    return answer

# game_board= [[1,1,0,0,1,0],[0,0,1,0,1,0],[0,1,1,0,0,1],[1,1,0,1,1,1],[1,0,0,0,1,0],[0,1,1,1,0,0]]
# table = [[1,0,0,1,1,0],[1,0,1,0,1,0],[0,1,1,0,1,1],[0,0,1,0,0,0],[1,1,0,1,1,0],[0,1,0,0,0,0]]

game_board= [[0,0,0],[1,1,0],[1,1,1]]
table = [[1,1,1],
         [1,0,0],
         [0,0,0]]

solution(game_board, table)

[[0 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [0 1 1]
 [0 1 1]]
[[1 1 1]
 [0 1 1]
 [0 0 0]]
drr 4
[[1 1 0]
 [1 1 0]
 [1 0 0]]


4

In [201]:
a = [[0, 0, 0],
    [1, 1, 0],
    [1, 1, 1]]

np.rot90(a, 0)

array([[0, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [ ]:
import numpy as np
from collections import defaultdict

def rotate(maps, i):
    nmap = np.array(maps)
    return np.rot90(nmap, i)

def make_figure(table):

    def dfs(coord, maps):
        nonlocal figure
        dx = [(1,'d'), (-1,'u'), (0,'r'), (0,'l')]
        dy = [(0,'d'), (0,'u'), (1,'r'), (-1,'l')]
        x, y = coord
        
        for i in range(4):
            nx = x + dx[i][0]
            ny = y + dy[i][0]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 0:
                continue
                
            if maps[nx][ny]:
                maps[x][y] = 0
                figure = figure+dx[i][1]
                dfs((nx, ny), maps)
                
        return figure
    
    figures = defaultdict(bool)
    total_maps = [np.array(table), rotate(table, 1),
                   rotate(table, 2), rotate(table, 3)]
    
    for maps in total_maps:
        for x in range(len(table)):
            for y in range(len(table[0])):
                if maps[x][y]:
                    figure = ''
                    figure = dfs((x,y), maps)
                    if figure != '':
                        figures[figure] = False
    
    return figures
            

def solution(game_board, table):
    answer = 0
    l = len(game_board)
    
    figures = make_figure(table)
    
    def dfs(coord, maps):
        nonlocal figure, cnt
        dx = [(1,'d'), (-1,'u'), (0,'r'), (0,'l')]
        dy = [(0,'d'), (0,'u'), (1,'r'), (-1,'l')]
        x, y = coord
        
        for i in range(4):
            nx = x + dx[i][0]
            ny = y + dy[i][0]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 1:
                continue
                
            if maps[nx][ny] == 0:
                maps[x][y] = 1
                figure = figure+dx[i][1]
                cnt += 1
                dfs((nx, ny), maps)
                
        return figure, cnt
    
    for x in range(l):
        for y in range(l):
            if game_board[x][y] == 0:
                figure = ''
                cnt = 1
                figure, cnt = dfs((x,y), game_board)
                if (figure in figures.keys()) and (not figures[figure]):
                    figures[figure] = True
                    print(figure, cnt)
                    answer += cnt
    
    return answer

In [33]:
import numpy as np
import copy

# 좌표를 회전 시키는 함수
def rotate(maps, i):
    nmap = np.array(maps)
    return np.rot90(nmap, i)

# 모든 figure 의 첫 시작(맨 위의 맨 좌측)을 (0,0) 으로 맞추고 비교 용이하도록
def normalize(coords):
    min_x = min(coord[0] for coord in coords)
    min_y = min(coord[1] for coord in coords)
    return [(coord[0] - min_x, coord[1] - min_y) for coord in coords]

# table 의 도형들을 회전시키면서 figure 를 얻는다.
def make_figure(table, i):

    def dfs(coord, maps):
        nonlocal figure
        dx = [1, -1, 0, 0]
        dy = [0, 0, 1, -1]
        x, y = coord
        
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 0:
                continue
                
            if maps[nx][ny]:
                maps[nx][ny] = 0
                figure = figure+[(nx, ny)]
                dfs((nx, ny), maps)
                
        return figure
    
    figures = []
    maps = rotate(table, i)
    
    for x in range(len(table)):
        for y in range(len(table[0])):
            if maps[x][y]:
                maps[x][y] = 0
                figure = [(x,y)]
                figure = dfs((x,y), maps)
                if len(figure) >= 1:
                    figures.append(figure)
    
    return figures

def solution(game_board, table):
    answer = 0
    l = len(game_board)
    
    # game_board 를 돌면서 puzzle 이 들어갈 공간을 찾는다.
    def dfs(coord, maps):
        nonlocal puzzle
        dx = [1, -1, 0, 0]
        dy = [0, 0, 1, -1]
        x, y = coord

        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            
            if nx < 0 or ny < 0 or nx >= len(maps) or ny >= len(maps):
                continue
            
            if maps[nx][ny] == 1:
                continue
                
            if maps[nx][ny] == 0:
                maps[nx][ny] = 1
                puzzle += [(nx, ny)]
                
                dfs((nx, ny), maps)
                
        return puzzle
    
    cnt = 0
    for i in range(4):
        # table 을 회전시켜가며 가지고 있는 figure 를 찾는다.
        #print(table)
        figures = make_figure(table, i)
        # game_board 와 table 의 비교를 용이하게 할 수 있도록 normalize
        n_figures = list(map(normalize, figures))
        maps = copy.deepcopy(game_board)
        #print(maps)
        #print(figures)
        #print(n_figures)
        puzzles = []
        for x in range(l):
            for y in range(l):
                if not maps[x][y]:
                    maps[x][y] = 1
                    puzzle = [(x,y)]
                    puzzle = dfs((x,y), maps)
                    if len(puzzle) >= 1:
                        puzzles.append(puzzle)
        #print(puzzles)
        n_puzzles = list(map(normalize, puzzles))
        print(n_puzzles)
        print(n_figures)
        for ti, f in enumerate(n_figures):
            if f in n_puzzles:
                cnt += len(f)
                gi = n_puzzles.index(f)
                #print(figures[j])
                for px, py in puzzles[gi]:
                    game_board[px][py] = 1
                n_puzzles.pop(gi)
                table = rotate(table, i)
                for tx, ty in figures[ti]:
                    table[tx][ty] = 0
                table = rotate(table, 4-i)
                        
    answer = cnt
    
    return answer

# game_board= [[0,0,0],[1,1,0],[1,1,1]]
# table = [[1,1,1],
#          [1,0,0],
#          [0,0,0]]
#game_board= [[1,1,0,0,1,0],[0,0,1,0,1,0],[0,1,1,0,0,1],[1,1,0,1,1,1],[1,0,0,0,1,0],[0,1,1,1,0,0]]
#table = [[1,0,0,1,1,0],[1,0,1,0,1,0],[0,1,1,0,1,1],[0,0,1,0,0,0],[1,1,0,1,1,0],[0,1,0,0,0,0]]
# game_board = [[1, 1, 0, 0, 1, 1],
#               [1, 1, 1, 0, 1, 1],
#               [1, 1, 1, 1, 1, 1],
#               [1, 1, 1, 1, 1, 1],
#               [1, 0, 0, 0, 1, 0],
#               [1, 1, 1, 1, 1, 1]]

# table = [[0, 0, 0, 0, 1, 1],
#          [1, 0, 0, 0, 0, 0],
#          [0, 0, 0, 0, 0, 0],
#          [0, 0, 0, 0, 0, 1],
#          [0, 0, 0, 0, 0, 1],
#          [0, 1, 1, 0, 0, 1]]
game_board = [[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
 [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
 [0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0],
 [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]]

table = [[1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
 [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
 [0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1],
 [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
 [1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1]]
solution(game_board, table)

[[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5)], [(0, 1), (1, 1), (1, 2), (2, 2), (1, 0), (2, 0)], [(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (0, 2)], [(0, 0), (0, 1), (1, 1), (0, 2), (0, 3), (0, 4)], [(0, 3), (1, 3), (2, 3), (1, 2), (1, 1), (1, 0)], [(0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(0, 0), (1, 0), (1, 1), (2, 1), (0, 1), (1, 2)], [(0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (1, 1)], [(0, 0), (0, 1), (1, 1), (2, 1), (2, 0), (0, 2)], [(0, 1), (1, 1), (2, 1), (3, 1), (3, 0), (1, 0)], [(0, 0), (1, 0), (1, 1), (2, 1), (3, 1), (0, 1)], [(0, 0), (1, 0), (2, 0), (2, 1), (1, 1), (0, 1)], [(0, 1), (1, 1), (2, 1), (2, 2), (2, 0), (1, 0)], [(0, 2), (1, 2), (1, 3), (1, 4), (1, 1), (1, 0)]]
[[(0, 0), (1, 0), (2, 0), (1, 1), (0, 1), (0, 2)], [(0, 0), (0, 1), (0, 2), (1, 2), (1, 3), (1, 4)], [(0, 1), (1, 1), (2, 1), (2, 0), (1, 2), (0, 2)], [(0, 0), (1, 0), (1, 1), (2, 1), (1, 2), (0, 2)], [(0, 0), (1, 0), (1, 1), (2, 1), (0, 1), (1, 2)], [(0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (0, 1)]

48

In [ ]:
[[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
 [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
 [0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
 [0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0],
 [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]]

[[1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
 [1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1],
 [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
 [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
 [0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1],
 [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
 [1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1]]
54

In [50]:
sum([True, False, True])

2

In [52]:
import heapq

def solution(k, n, reqs):
    answer = 0
    # 각 상담 유형별로 상담사 한명씩 배치
    # 상담사는 상담 중 여부, 상담이 끝나는 시간
    consulting = {i:(False, 0) for i in range(1, k+1)}
    # 남은 상담사
    remain = n - k
    # 대기 시간 종합
    wait = []
    # 시작 시간, 상담 시간, 상담 유형
    for start, duration, consult in reqs:
        
        if consulting[consult][1] < start:
            consulting[consult][1] = False
        
        if not consulting[consult][0]:
            consulting[consult][0] = True
            consulting[consult][1] = start + duration
            
        else:
            heapq.heappush(wait, -(consulting[consult][1] - start))
    
    for r in range(remain):
        heapq.heappop(wait)
    
    answer = sum([wait_time for wait_time in wait])
    
    return answer

k = 3
n = 5
reqs = [[10, 60, 1], [15, 100, 3], [20, 30, 1], [30, 50, 3], [50, 40, 1], [60, 30, 2], [65, 30, 1], [70, 100, 2]]

solution(k, n, reqs)

TypeError: 'tuple' object does not support item assignment

In [60]:
k = 3
n = 5
reqs = [[10, 60, 1], [15, 100, 3], [20, 30, 1], [30, 50, 3], [50, 40, 1], [60, 30, 2], [65, 30, 1], [70, 100, 2]]

from itertools import combinations_with_replacement, combinations
kl = [i for i in range(1, k+1)]
list(combinations_with_replacement(kl, n))
#list(combinations(range(1, n), k-1))

[(1, 1, 1, 1, 1),
 (1, 1, 1, 1, 2),
 (1, 1, 1, 1, 3),
 (1, 1, 1, 2, 2),
 (1, 1, 1, 2, 3),
 (1, 1, 1, 3, 3),
 (1, 1, 2, 2, 2),
 (1, 1, 2, 2, 3),
 (1, 1, 2, 3, 3),
 (1, 1, 3, 3, 3),
 (1, 2, 2, 2, 2),
 (1, 2, 2, 2, 3),
 (1, 2, 2, 3, 3),
 (1, 2, 3, 3, 3),
 (1, 3, 3, 3, 3),
 (2, 2, 2, 2, 2),
 (2, 2, 2, 2, 3),
 (2, 2, 2, 3, 3),
 (2, 2, 3, 3, 3),
 (2, 3, 3, 3, 3),
 (3, 3, 3, 3, 3)]

In [65]:
import heapq
from itertools import combinations, combinations_with_replacement

def solution(k, n, reqs):
    answer = 9999999999
    # 중복 조합을 통해서 상담사들을 각 상담 유형에 따라 분배
    for comb in combinations(range(1, n), k-1):
        
        # 맨 처음 0, 맨 마지막 n 을 두고 1 이상 n-1 이하 중 k-1 개의 수를 뽑는다.
        # 그렇게 되면 인접한 인덱스의 값끼리 차이를 구했을 때 k 개의 값이 나온다.
        # 이는 각 상담 유형별 몇 명의 상담사가 배치되었는지를 나타낸다.
        consultant = [0, *comb, n]
        print(consultant)
        
        # 특정 상담사 분배의 총 대기 시간
        total_wait = 0
        
        # heapq 를 통해 상담 유형 별 상담 리스트를 만든다. 각 유형별 리스트에는 특정 상담이 끝나는 시간을 넣는다.
        consult_list = [[] for _ in range(k+1)]
        for start, duration, consult in reqs:
            print(consult_list, total_wait)
            # 진행 중인 상담이 있고, 현재 상담 시작 시간이 진행 중 상담이 끝날 시간보다 크거나 같을 때
            while consult_list[consult] and consult_list[consult][0] <= start:
                # min heap 특성에 따라 가장 빨리 끝나는 진행 중인 상담을 제거한다.
                heapq.heappop(consult_list[consult])
            
            # 특정 상담 유형에 배정된 상담사 수만큼 진행 중인 상담이 있다면
            # 진행 중인 상담이 끝나고 현재 상담을 리스트에 집어넣는다.
            if len(consult_list[consult]) == consultant[consult] - consultant[consult-1]:
                # 현재 상담이 시작될 때까지 기다려야 하는 시간
                wait = heapq.heappop(consult_list[consult]) - start
                total_wait += wait
                start += wait
            
            heapq.heappush(consult_list[consult], start + duration)
        
        answer = min(answer, total_wait)
            
    return answer

k = 3
n = 5
reqs = [[10, 60, 1], [15, 100, 3], [20, 30, 1], [30, 50, 3], [50, 40, 1], [60, 30, 2], [65, 30, 1], [70, 100, 2]]
solution(k, n, reqs)

[0, 1, 2, 5]
[[], [], [], []] 0
[[], [70], [], []] 0
[[], [70], [], [115]] 0
[[], [100], [], [115]] 50
[[], [100], [], [80, 115]] 50
[[], [140], [], [80, 115]] 100
[[], [140], [90], [80, 115]] 100
[[], [170], [90], [80, 115]] 175
[0, 1, 3, 5]
[[], [], [], []] 0
[[], [70], [], []] 0
[[], [70], [], [115]] 0
[[], [100], [], [115]] 50
[[], [100], [], [80, 115]] 50
[[], [140], [], [80, 115]] 100
[[], [140], [90], [80, 115]] 100
[[], [170], [90], [80, 115]] 175
[0, 1, 4, 5]
[[], [], [], []] 0
[[], [70], [], []] 0
[[], [70], [], [115]] 0
[[], [100], [], [115]] 50
[[], [100], [], [165]] 135
[[], [140], [], [165]] 185
[[], [140], [90], [165]] 185
[[], [170], [90], [165]] 260
[0, 2, 3, 5]
[[], [], [], []] 0
[[], [70], [], []] 0
[[], [70], [], [115]] 0
[[], [50, 70], [], [115]] 0
[[], [50, 70], [], [80, 115]] 0
[[], [70, 90], [], [80, 115]] 0
[[], [70, 90], [90], [80, 115]] 0
[[], [90, 100], [90], [80, 115]] 5
[0, 2, 4, 5]
[[], [], [], []] 0
[[], [70], [], []] 0
[[], [70], [], [115]] 0
[[], [50, 

25

In [66]:
a = 1
b = 3
a = b
b = 4
a

3

In [70]:
array = [5, 7, 9, 8, 3, 1, 6, 2, 4, 0]

def quick_sort(array, start, end):
    if start >= end: # 원소가 1개인 경우 종료
        return
    pivot = start # 피벗은 첫 번째 원소
    left = start + 1
    right = end
    while left <= right:
        # 피벗보다 큰 데이터를 찾을 때까지 반복 (왼쪽, 선형 탐색)
        while left <= end and array[left] <= array[pivot]:
            left += 1
        # 피벗보다 작은 데이터를 찾을 때까지 반복 (오른쪽, 선형 탐색)
        while right > start and array[right] >= array[pivot]:
            right -= 1
        if left > right: # 엇갈렸다면 작은 데이터와 피벗을 교체
            array[right], array[pivot] = array[pivot], array[right]
        else: # 엇갈리지 않았다면 작은 데이터와 큰 데이터를 교체
            array[left], array[right] = array[right], array[left]
    # 분할 이후 왼쪽 부분과 오른쪽 부분에서 각각 정렬 수행
    quick_sort(array, start, right-1)
    quick_sort(array, right+1, end)
    # 이상적인 경우 위 분할에서 왼쪽과 오른쪽이 균형있게 분할되어 빠르게 동작 기대
    
quick_sort(array, 0, len(array)-1)

array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
array = [5, 7, 9, 0, 3, 1, 6, 2, 4, 8]

def quick_sort(array):
    # 리스트가 하나 이하의 원소만을 담고 있다면 종료
    if len(array) <= 1:
        return array
    pivot = array[0] # 피벗은 첫번째 원소
    tail = array[1:] # 피벗을 제외한 리스트
    
    left_side = [x for x in tail if x <= pivot] # 분할된 왼쪽 부분
    right_side = [x for x in tail if x > pivot] # 분할된 오른쪽 부분
    print(left_side)
    print(right_side)
    # 분할 이후 왼쪽 부분과 오른쪽 부분에서 각각 정렬 수행하고 전체 리스트 반환
    return quick_sort(left_side) + [pivot] + quick_sort(right_side)
    
b = quick_sort(array)

b

[0, 3, 1, 2, 4]
[7, 9, 6, 8]
[]
[3, 1, 2, 4]
[1, 2]
[4]
[]
[2]
[6]
[9, 8]
[8]
[]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
'30' * 3

'303030'

In [85]:
a = [3, 0, 6, 1, 5]
a.sort(reverse=True)
print(list(enumerate(a, start=1)))
print(list(map(min, enumerate(a, start=1))))
print(max(list(map(min, enumerate(a, start=1)))))

[(1, 6), (2, 5), (3, 3), (4, 1), (5, 0)]
[1, 2, 3, 1, 0]
3


In [91]:
"I 16".split()

['I', '16']

In [94]:
a = {'1':[[1, 0], [-1,0]], '2':[[2, 0], [-2, 0]]}
aa = a.pop('1')
aa[1][1] = 1

a

{'2': [[2, 0], [-2, 0]]}

In [95]:
a = []

for i, r in enumerate(a):
    print(i)

In [102]:
"1234"[1:]

'234'

In [103]:
"9" > "1"

True

In [104]:
False or True

True

In [172]:
import re
from itertools import product

def solution(user_id, banned_id):
    answer = 0
    possibles = []
    
    for ban in banned_id:
        cnt = 0
        pattern = ban.replace('*', '[a-z0-9]')
        possible = []
        for user in user_id:
            if [user] == re.findall(pattern, user):
                possible.append(user)
        
        if possible:
            possibles.append(possible)
        
    for cand in product(*possibles):
        if len(cand) == len(set(cand)):
            print(cand)
            answer += 1
    
    return answer

user_id = ["frodo", "fradi", "crodo", "abc123", "frodoc"]
banned_id = ["*rodo", "*rodo", "******"]

solution(user_id, banned_id)

('frodo', 'crodo', 'abc123')
('frodo', 'crodo', 'frodoc')
('crodo', 'frodo', 'abc123')
('crodo', 'frodo', 'frodoc')


4

In [239]:
## 1
from collections import defaultdict
from sys import setrecursionlimit
setrecursionlimit(10000)

# 전체 트리의 x 값 범위
MIN, MAX = -1, 100001
# 전체 트리 깊이
TREE_DEPTH = 0

def solution(nodeinfo):
    global TREE_DEPTH

    # 전위, 중위, 후위 순위를 위한 트리를 각각 생성
    pre_tree = defaultdict(list)
    mid_tree = defaultdict(list)
    post_tree = defaultdict(list)
    # y값 level
    level = set()

    for i in range(len(nodeinfo)):
        x, y = nodeinfo[i]
        # 각 트리는 {y값 : [(해당 y값을 가진 노드의 x 좌표와 노드번호),...]}
        pre_tree[y].append((x, i+1))
        mid_tree[y].append((x, i+1))
        post_tree[y].append((x, i+1))
        level.add(y)

    for i in level:
        # x 값이 작은 것(왼쪽에 위치한 노드) 부터 판단하기 위하여 역순 정렬
        pre_tree[i].sort(reverse=True)
        mid_tree[i].sort(reverse=True)
        post_tree[i].sort(reverse=True)

    level = sorted(list(level), reverse=True)
    TREE_DEPTH = len(level)
    
    # 각 순회의 인자는 특정 노드가 가질 수 있는 x 값의 최소, 최대, 특정 노드의 depth, 결과를 담을 리스트, 각 순회용 트리, level
    preorder = []
    pre_order(MIN, MAX, 0, preorder, pre_tree, level)
    midorder = []
    mid_order(MIN, MAX, 0, midorder, mid_tree, level)
    postorder = []
    post_order(MIN, MAX, 0, postorder, post_tree, level)

    return [preorder, postorder, midorder]


def pre_order(left, right, depth, result, tree, level):
    '''
    전위 순회
    Root -> L -> R
    '''
    if depth == TREE_DEPTH:
        return
    if len(tree[level[depth]]) <= 0:
        return
    if not (left < tree[level[depth]][-1][0] < right):
        return
    
    x, index = tree[level[depth]].pop()
    result.append(index)
    pre_order(left, x, depth+1, result, tree, level)
    pre_order(x, right, depth+1, result, tree, level)

def mid_order(left, right, depth, result, tree, level):
    '''
    중위 순회
    L -> Root -> R
    '''
    if depth == TREE_DEPTH:
        return
    if len(tree[level[depth]]) <= 0:
        return
    if not (left < tree[level[depth]][-1][0] < right):
        return
    
    x, index = tree[level[depth]].pop()
    mid_order(left, x, depth+1, result, tree, level)
    result.append(index)
    mid_order(x, right, depth+1, result, tree, level)

def post_order(left, right, depth, result, tree, level):
    '''
    후위 순회
    L -> R -> Root
    '''
    if depth == TREE_DEPTH:
        return
    if len(tree[level[depth]]) <= 0:
        return
    if not (left < tree[level[depth]][-1][0] < right):
        return
    
    x, index = tree[level[depth]].pop()
    post_order(left, x, depth+1, result, tree, level)
    post_order(x, right, depth+1, result, tree, level)
    result.append(index)
    
nodeinfo = [[5,3],[11,5],[13,3],[3,5],[6,1],[1,3],[8,6],[7,2],[2,2]]

solution(nodeinfo)

[[7, 4, 6, 9, 1, 8, 5, 2, 3],
 [9, 6, 5, 8, 1, 4, 3, 2, 7],
 [6, 9, 4, 1, 5, 8, 7, 2, 3]]

In [241]:
## 2

from sys import setrecursionlimit
setrecursionlimit(10000)

def solution(nodeinfo):
    # 노드번호 추가하여 (x,y,n) 형태 만들고 x좌표 기준 정렬
    nodeinfo = sorted([(x,y,i+1) for i,(x,y) in enumerate(nodeinfo)], key=lambda x:x[0])
    result = [[], [], []]
    print(nodeinfo)

    # 트리를 순회 하는 함수
    def make_order(nodeinfo):
        if nodeinfo:
            # 루트 노드 정보 찾기 (3분할 과정. 각 순회에서 루트 노드를 기준으로 루트, 좌측 서브트리, 우측 서브트리 탐색)
            # x 좌표 기준으로 정렬된 nodeinfo 에서 index, y, 노드번호
            root = (0,-1,0)
            for idx, (x,y,n) in enumerate(nodeinfo):
                # 특정 순회에서 y 값이 가장 큰 루트 노드 찾기
                if y > root[1]:
                    root = (idx, y, n)

            # 좌측 서브트리, 우측 서브트리
            left_sub, right_sub = nodeinfo[:root[0]], nodeinfo[root[0]+1:]
            
            # 좌, 우 서브트리 탐색 전 루트노드 출력 -> 전위 순회
            result[0].append(root[-1])
            # 좌측 서브트리 탐색
            make_order(left_sub)
            # 좌측 서브트리 탐색 후 루트노드 출력, 우측 서브트리 탐색 -> 중위 순회
            result[2].append(root[-1])
            # 우측 서브트리 탐색
            make_order(right_sub)
            # 좌, 우 서브트리 탐색 후 루트노드 출력 -> 후위 순회
            result[1].append(root[-1])
    
    make_order(nodeinfo)
    return result

nodeinfo = [[5,3],[11,5],[13,3],[3,5],[6,1],[1,3],[8,6],[7,2],[2,2]]

solution(nodeinfo)

[(1, 3, 6), (2, 2, 9), (3, 5, 4), (5, 3, 1), (6, 1, 5), (7, 2, 8), (8, 6, 7), (11, 5, 2), (13, 3, 3)]


[[7, 4, 6, 9, 1, 8, 5, 2, 3],
 [9, 6, 5, 8, 1, 4, 3, 2, 7],
 [6, 9, 4, 1, 5, 8, 7, 2, 3]]

In [260]:
import re
import itertools

banned_id = ["fr*d*", "*rodo", "******", "******"]
user_id = ["frodo", "fradi", "crodo", "abc123", "frodoc"]

banned_id = ["'" + _.replace('*', '\w') + "'"  for _ in banned_id]
print(f'banned_id 정규식 전환 : {banned_id}')
print(f'user_id 문자열 전환 : {str(user_id)}')
possible_list = [re.findall(_, str(user_id)) for _ in banned_id]   
print(f'banned_id 별 가능한 user_id : {possible_list}')
possible_list = list(itertools.product(*possible_list))
print(f'banned_id 별 가능한 user_id 의 모든 조합 : {possible_list}')
possible_list = [frozenset(p) for p in possible_list if len(set(p)) == len(banned_id)]
print(f'banned_id 별 가능한 user_id 의 모든 조합 내에서 중복 제거 : {possible_list}')
possible_list = set(possible_list)
print(f'banned_id 별 가능한 user_id 의 모든 조합 중 중복 제거  : {possible_list}')
len(possible_list)

banned_id 정규식 전환 : ["'fr\\wd\\w'", "'\\wrodo'", "'\\w\\w\\w\\w\\w\\w'", "'\\w\\w\\w\\w\\w\\w'"]
user_id 문자열 전환 : ['frodo', 'fradi', 'crodo', 'abc123', 'frodoc']
banned_id 별 가능한 user_id : [["'frodo'", "'fradi'"], ["'frodo'", "'crodo'"], ["'abc123'", "'frodoc'"], ["'abc123'", "'frodoc'"]]
banned_id 별 가능한 user_id 의 모든 조합 : [("'frodo'", "'frodo'", "'abc123'", "'abc123'"), ("'frodo'", "'frodo'", "'abc123'", "'frodoc'"), ("'frodo'", "'frodo'", "'frodoc'", "'abc123'"), ("'frodo'", "'frodo'", "'frodoc'", "'frodoc'"), ("'frodo'", "'crodo'", "'abc123'", "'abc123'"), ("'frodo'", "'crodo'", "'abc123'", "'frodoc'"), ("'frodo'", "'crodo'", "'frodoc'", "'abc123'"), ("'frodo'", "'crodo'", "'frodoc'", "'frodoc'"), ("'fradi'", "'frodo'", "'abc123'", "'abc123'"), ("'fradi'", "'frodo'", "'abc123'", "'frodoc'"), ("'fradi'", "'frodo'", "'frodoc'", "'abc123'"), ("'fradi'", "'frodo'", "'frodoc'", "'frodoc'"), ("'fradi'", "'crodo'", "'abc123'", "'abc123'"), ("'fradi'", "'crodo'", "'abc123'", "'frodoc'"), ("'fr

3

In [23]:
# 완전 탐색 - DFS, 백트래킹
def solution(k, dungeons):
    answer = 0
    visited = [False] * len(dungeons)
    
    def dfs(k, cnt, dungeons, i):
        nonlocal answer, visited
        print(f'{i} start')
        if cnt > answer:
            answer = cnt

        for idx in range(len(dungeons)):
            required, consumption = dungeons[idx]
            
            if k >= required and not visited[idx]:
                visited[idx] = True
                dfs(k - consumption, cnt+1, dungeons, i+1)
                # 백트래킹
                print(f'{i} back tracking')
                visited[idx] = False
        print(f'{i} end')
    dfs(k, 0, dungeons, 0)
    return answer

dungeons = [[80,20],[50,40],[30,10]]
k = 80

solution(k, dungeons)

0 start
1 start
2 start
2 end
1 back tracking
2 start
3 start
3 end
2 back tracking
2 end
1 back tracking
1 end
0 back tracking
1 start
2 start
2 end
1 back tracking
1 end
0 back tracking
1 start
2 start
2 end
1 back tracking
1 end
0 back tracking
0 end


3

In [34]:
# Union-Find
import copy
from collections import Counter

def solution(n, wires):
    answer = 999
        
    def find(parent, idx):
        if parent[idx] != idx:
            parent[idx] = find(parent, parent[idx])
        return parent[idx]
        
    def union(parent, a, b):
        a = find(parent, a)
        b = find(parent, b)
        if a < b:
            parent[b] = a
        else:
            parent[a] = b
    
    for i in range(len(wires)):
        n_wires = copy.deepcopy(wires)
        n_wires.pop(i)
        
        parent = [0] * (n+1)
        for j in range(1, n+1):
            parent[j] = j
        
        for a, b in n_wires:
            union(parent, a, b)
        
        print(parent[1:])
        count = Counter(parent[1:])
        diff = abs(list(count.values())[0] - list(count.values())[1])
        
        answer = min(answer, diff)
    
    return answer

wires = [[1,2],[2,7],[3,7],[3,4],[4,5],[6,7]]
n = 7

solution(n, wires)

[1, 2, 2, 2, 2, 2, 2]
[1, 1, 3, 3, 3, 3, 3]
[1, 1, 3, 3, 3, 1, 1]
[1, 1, 1, 4, 4, 1, 1]
[1, 1, 1, 1, 5, 1, 1]
[1, 1, 1, 1, 1, 6, 1]


1

In [43]:
from itertools import product

a = [1,2,3,4,5,6]

for i in product(a, repeat=2):
    print(i)

(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(3, 5)
(3, 6)
(4, 1)
(4, 2)
(4, 3)
(4, 4)
(4, 5)
(4, 6)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 5)
(5, 6)
(6, 1)
(6, 2)
(6, 3)
(6, 4)
(6, 5)
(6, 6)
